#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

foamCleanPolyMesh -region air
foamCleanPolyMesh -region buildings
foamCleanPolyMesh -region terrain


rm -f constant/air/F*
rm -f constant/air/constructMap*
rm -f constant/air/finalAgglom*
rm -f constant/air/globalFaceFaces*
rm -f constant/air/subMap*
rm -f constant/air/skyViewCoeff*
rm -f constant/air/sunViewCoeff*
rm -f constant/air/sunskyMap*
rm -f constant/air/solarLoadFineFaces*
rm -f processor*

rm -f log*
rm -f 0/air/viewFactorField*

rm -f 0/*.gz
rm -f 0/air/faceAgglomerate.gz
rm -rf ./constant/extendedFeatureEdgeMesh
rm -f ./constant/triSurface/*.eMesh*

rm -rf 0/buildings
cp -r 0/buildings_bak 0/buildings

rm -rf 0/terrain
cp -r 0/terrain_bak 0/terrain

rm -rf 0/air
cp -r 0/air_bak 0/air


# ----------------------------------------------------------------- end-of-file
