#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NP=32

# -------------------------------
# Update decomposeParDict files
# -------------------------------
echo "Updating decomposeParDict files..."

updateDict() {
    dictPath="$1"

    if [ -f "$dictPath" ]; then
        echo "Updating $dictPath"

        # Update numberOfSubdomains
        sed -i "s/^numberOfSubdomains.*/numberOfSubdomains $NP;/" "$dictPath"


    else
        echo "Warning: $dictPath not found"
    fi
}

# Apply to all regions
updateDict system/decomposeParDict
updateDict system/air/decomposeParDict
updateDict system/terrain/decomposeParDict
updateDict system/buildings/decomposeParDict


# -------------------------------
# Create air mesh (parallel snappyHexMesh)
# -------------------------------
echo "Creating mesh for air region..."
blockMesh > log1.blockMesh.air 2>&1
surfaceFeatures > log2.surfaceFeatures.air 2>&1

echo "Decomposing for parallel snappyHexMesh..."
decomposePar -force > log3.decomposePar_snappy 2>&1

echo "Running snappyHexMesh in parallel..."
mpirun -np $NP snappyHexMesh -parallel -overwrite > log4.snappyHexMesh.air 2>&1

echo "Reconstructing mesh..."
reconstructParMesh -constant > log5.reconstructParMesh.air 2>&1

echo "Cleaning up processor dirs from snappy..."
rm -rf processor*

# Move mesh to air region
rm -rf constant/air/polyMesh
mv constant/polyMesh constant/air/

changeDictionary -region air > log7.changeDictionary.air 2>&1
echo "Air mesh done."

echo "Checking mesh..."
checkMesh -latestTime -region air -allTopology > log6.checkMesh.air 2>&1


echo "Creating mesh for solid regions"
for i in terrain buildings;
do

    echo "Extruding mesh for $i region..."
    cp -r system/$i/extrudeMeshDict system/extrudeMeshDict
    extrudeMesh > log8.extrudeMesh.$i 2>&1
    rm -rf constant/$i/polyMesh
    mv constant/polyMesh constant/$i/
    
    echo "Creating patches for $i region..."
    cp -r system/$i/createPatchDict system/createPatchDict
    createPatch -region $i -overwrite > log9.createPatch.$i 2>&1

    if [ -f system/$i/topoSetDict ]; then
        echo "Running topoSet for $i region..."
        cp -r system/$i/topoSetDict system/topoSetDict
        topoSet -region $i > log8b.topoSet.$i 2>&1
    fi

    if [ -f system/$i/setset.batch ]; then
        echo "Running setSet for $i region..."
        cp -r system/$i/setset.batch system/
        setSet -region $i -noVTK -batch system/$i/setset.batch > log11.setSet.$i 2>&1
    fi

    echo "Changing dictionary for $i region..."
    cp -r system/$i/changeDictionaryDict system/changeDictionaryDict
    changeDictionary -region $i > log10.changeDictionary.$i 2>&1


    echo "Checking mesh for $i region..."
    checkMesh -region $i -allTopology > log12.checkMesh.$i 2>&1

done




# ----------------------------------------------------------------- end-of-file
